const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'src', 'lib', 'singers');
if (!fs.existsSync(OUT)) fs.mkdirSync(OUT, { recursive: true });

function gen(arr, region) {
  let s = `import type { SingerStyle } from '../singer-styles';\n\nexport const ${region}Singers: SingerStyle[] = [\n`;
  for (const e of arr) {
    s += `  { id:'${e[0]}', name:'${e[1]}', nameEn:'${e[2]}', region:'${region}', gender:'${e[3]}', tags:[${e[4].map(t=>`'${t}'`).join(',')}], techniques:[${e[5].map(t=>`'${t}'`).join(',')}], description:'${e[6]}', representativeWorks:[${e[7].map(w=>`'${w.replace(/'/g,"\\'")}'`).join(',')}] },\n`;
  }
  s += '];\n';
  return s;
}

// ===== 华语歌手 ~250 =====
const cn = [
// [id, name, nameEn, gender, tags[], techniques[], desc, works[]]
// 华语男歌手
['jay-chou','周杰伦','Jay Chou','male',['R&B','中国风','说唱'],['饶舌律动','R&B转音','假声切换','咬字含糊'],'独特的咬字方式和R&B律动感，融合中国风元素',['晴天','七里香','青花瓷']],
['jj-lin','林俊杰','JJ Lin','male',['流行','抒情','高音'],['高音张力','假声连接','情感爆发','气息控制'],'极具张力的高音和细腻的情感表达',['江南','修炼爱情','可惜没如果']],
['eason-chan','陈奕迅','Eason Chan','male',['抒情','粤语','叙事'],['情感叙事','中低音磁性','气息稳定','情感层次'],'深情的中低音和细腻的情感表达',['十年','浮夸','爱情转移']],
['mao-buyi','毛不易','Mao Buyi','male',['民谣','叙事','治愈'],['说唱式咬字','叙事感','低音沉稳','情感真挚'],'说唱式的咬字方式和强烈的叙事感',['像我这样的人','消愁','平凡的一天']],
['xue-zhiqian','薛之谦','Joker Xue','male',['流行','抒情','情歌'],['情感爆发','高音撕裂','情绪张力','沙哑音色'],'极具情感张力的演唱方式',['演员','丑八怪','认真的雪']],
['wang-feng','汪峰','Wang Feng','male',['摇滚','励志','沧桑'],['沙哑摇滚','高音呐喊','情感粗犷','力量感'],'沧桑的摇滚嗓音和励志的歌词表达',['春天里','存在','飞得更高']],
['liu-huan','刘欢','Liu Huan','male',['大气','实力','经典'],['浑厚男声','高音穿透','气息绵长','情感厚重'],'浑厚大气的嗓音，中国乐坛教父级人物',['千万次的问','好汉歌','弯弯的月亮']],
['sun-nan','孙楠','Sun Nan','male',['高音','实力','流行'],['超高音','胸声共鸣','穿透力','气息控制'],'极具穿透力的高音',['你快回来','不见不散','拯救']],
['liu-dehua','刘德华','Andy Lau','male',['经典','粤语','情歌'],['温润中音','情感真挚','粤语发音','舞台感染力'],'温润深情的中音，华语乐坛常青树',['忘情水','中国人','爱你一万年']],
['zhang-xueyou','张学友','Jacky Cheung','male',['歌神','抒情','粤语'],['完美颤音','情感细腻','音准极佳','气息绵长'],'被誉为歌神，颤音技巧登峰造极',['吻别','一路上有你','李香兰']],
['zhou-hua-jian','周华健','Emil Chau','male',['温暖','民谣','经典'],['温暖中音','叙事感强','情感自然','吉他弹唱'],'温暖亲切的嗓音',['朋友','花心','让我欢喜让我忧']],
['richie-jen','任贤齐','Richie Ren','male',['流行','抒情','温暖'],['清澈中音','情感质朴','旋律感强','自然演唱'],'清澈温暖的嗓音',['心太软','对面的女孩看过来','伤心太平洋']],
['zhang-yu-sheng','张雨生','Tom Chang','male',['高音','摇滚','创作'],['超高音','摇滚嘶吼','创作才华','情感激烈'],'极具爆发力的高音，英年早逝的音乐天才',['大海','我的未来不是梦','天天想你']],
['wang-jie','王杰','Dave Wong','male',['沧桑','抒情','粤语'],['沧桑音色','情感深沉','高音悲怆','独特颤音'],'沧桑深情的嗓音',['一场游戏一场梦','安妮','是否']],
['qi-qin','齐秦','Chyi Chin','male',['民谣','摇滚','沧桑'],['清亮高音','民谣感','摇滚力量','情感真挚'],'清亮而沧桑的独特嗓音',['大约在冬季','狼','夜夜夜夜']],
['zhang-xin-zhe','张信哲','Jeff Chang','male',['情歌','抒情','温柔'],['温柔高音','情感细腻','假声优美','气息平稳'],'情歌王子',['爱如潮水','过火','信仰']],
['wu-bai','伍佰','Wu Bai','male',['摇滚','闽南','独特'],['沙哑摇滚','闽南语','独特咬字','现场感染力'],'极具个人风格的摇滚歌手',['挪威的森林','浪人情歌','突然的自我']],
['li-zhi','李志','Li Zhi','male',['民谣','独立','文艺'],['沙哑低沉','叙事感','民谣吉他','情感克制'],'中国独立民谣代表人物',['天空之城','关于郑州的记忆','梵高先生']],
['zhao-lei','赵雷','Zhao Lei','male',['民谣','叙事','质朴'],['质朴演唱','叙事感强','中低音温暖','吉他弹唱'],'质朴温暖的民谣歌手',['成都','南方姑娘','鼓楼']],
['song-dongye','宋冬野','Song Dongye','male',['民谣','文艺','低沉'],['低沉嗓音','文艺气息','叙事感','吉他弹唱'],'低沉磁性的民谣嗓音',['斑马斑马','董小姐','安和桥北']],
['chen-chusheng','陈楚生','Chen Chusheng','male',['民谣','抒情','清新'],['清澈中音','情感真挚','吉他弹唱','气息稳定'],'清澈温暖的嗓音',['有没有人告诉你','思念一个荒废的名字']],
['pu-shu','朴树','Pu Shu','male',['摇滚','文艺','理想'],['清澈高音','理想主义','情感纯粹','独特音色'],'理想主义音乐人',['那些花儿','平凡之路','生如夏花']],
['xu-wei','许巍','Xu Wei','male',['摇滚','励志','沧桑'],['沙哑摇滚','高音穿透','情感深沉','力量感'],'摇滚诗人',['蓝莲花','曾经的你','故乡']],
['zheng-jun','郑钧','Zheng Jun','male',['摇滚','叛逆','力量'],['摇滚嘶吼','中低音厚实','情感激烈','舞台爆发'],'中国摇滚先驱之一',['灰姑娘','赤裸裸','私奔']],
['cui-jian','崔健','Cui Jian','male',['摇滚','先驱','思想'],['粗犷摇滚','说唱式','思想性','现场震撼'],'中国摇滚之父',['一无所有','花房姑娘','假行僧']],
['dou-wei','窦唯','Dou Wei','male',['摇滚','实验','先锋'],['实验性唱法','高音尖锐','风格多变','前卫'],'中国摇滚先锋',['高级动物','艳阳天','山河水']],
['ding-wu','丁武','Ding Wu','male',['摇滚','金属','嘶吼'],['高音嘶吼','金属唱腔','力量感极强','舞台疯狂'],'唐朝乐队主唱',['梦回唐朝','飞翔鸟','太阳']],
['hua-chényǔ','华晨宇','Hua Chenyu','male',['高音','实验','舞台'],['超高音','实验性','舞台爆发','风格多变'],'极具实验精神的新生代歌手',['烟火里的尘埃','齐天','好想爱这个世界啊']],
['zhou-shen','周深','Zhou Shen','male',['天籁','假声','空灵'],['假声男高音','空灵音色','音域极广','跨性别音色'],'独特的假声男高音',['大鱼','达拉崩吧','起风了']],
['zhang-jie','张杰','Jason Zhang','male',['高音','流行','实力'],['高音穿透','气息控制','情感爆发','音域宽广'],'实力派高音歌手',['逆战','这就是爱','明天过后']],
['li-ronghao','李荣浩','Li Ronghao','male',['创作','流行','R&B'],['中低音磁性','创作才华','R&B感觉','慵懒唱腔'],'全能创作人',['模特','李白','年少有为']],
['xu-song','许嵩','Vae Xu','male',['创作','中国风','网络'],['清亮中音','中国风','创作全能','假声运用'],'网络音乐先驱',['断桥残雪','清明雨上','庐州月']],
['wang-leehom','王力宏','Leehom Wang','male',['R&B','中国风','全能'],['R&B转音','假声技巧','创作才华','多乐器'],'全能音乐人',['龙的传人','花田错','唯一']],
['david-tao','陶喆','David Tao','male',['R&B','灵魂','创作'],['R&B转音','灵魂唱腔','假声流畅','创作才华'],'华语R&B教父',['爱很简单','飞机场的10:30','普通朋友']],
['show-lo','罗志祥','Show Lo','male',['唱跳','流行','舞台'],['唱跳实力','中音稳定','舞台魅力','综艺感'],'亚洲舞王',['精舞门','撑腰','恋爱达人']],
['harlem-yu','庾澄庆','Harlem Yu','male',['摇滚','R&B','多才'],['摇滚唱腔','R&B转音','多才多艺','舞台感染'],'音乐顽童',['情非得已','让我一次爱个够','春泥']],
['lin-zhixuan','林志炫','Terry Lin','male',['高音','实力','抒情'],['超高音','假声连接','气息控制','音色纯净'],'极具实力的高音歌手',['单身情歌','蒙娜丽莎的眼泪']],
['xiao-jingteng','萧敬腾','Jam Hsiao','male',['摇滚','高音','爆发'],['摇滚嘶吼','高音爆发','情感激烈','舞台张力'],'充满爆发力的摇滚歌手',['王妃','新不了情','原谅我']],
['fang-datong','方大同','Khalil Fong','male',['灵魂','R&B','创作'],['灵魂唱腔','R&B转音','吉他技巧','创作才华'],'华语灵魂乐代表',['Love Song','三人游','特别的人']],
['will-pan','潘玮柏','Wilber Pan','male',['说唱','流行','唱跳'],['说唱技巧','中低音','唱跳能力','节奏感'],'说唱偶像',['反转地球','壁虎漫步','快乐崇拜']],
['wu-kequn','吴克群','Kenji Wu','male',['流行','创作','抒情'],['中音稳定','创作才华','情感表达','舞台感'],'创作型偶像歌手',['大舌头','将军令','为你写诗']],
['hacken-lee','李克勤','Hacken Lee','male',['粤语','实力','经典'],['完美气息','高音稳定','颤音技巧','零瑕疵'],'零瑕疵歌手',['红日','月半小夜曲','护花使者']],
['george-lam','林子祥','George Lam','male',['粤语','高音','经典'],['超高音','气息绵长','音域极广','实力深厚'],'粤语乐坛高音之王',['男儿当自强','真的汉子','十分十二寸']],
['sam-hui','许冠杰','Sam Hui','male',['粤语','经典','民谣'],['温暖中音','粤语鼻祖','民谣风格','创作才华'],'粤语流行乐坛鼻祖',['浪子心声','沧海一声笑','天才白痴梦']],
['roman-tam','罗文','Roman Tam','male',['粤语','经典','舞台'],['舞台魅力','中音浑厚','粤语经典','表演艺术'],'粤语乐坛殿堂级歌手',['小李飞刀','铁血丹心','尘缘']],
['danny-chan','陈百强','Danny Chan','male',['粤语','经典','温柔'],['温柔高音','假声优美','情感细腻','贵族气质'],'优雅温柔的粤语经典歌手',['一生何求','偏偏喜欢你','烟雨凄迷']],
['leslie-cheung','张国荣','Leslie Cheung','male',['粤语','传奇','全能'],['中低音磁性','情感深邃','舞台魅力','跨领域艺术'],'华语乐坛传奇巨星',['风继续吹','Monica','当爱已成往事']],
['beyond-ka-kui','黄家驹','Wong Ka Kui','male',['摇滚','粤语','理想'],['摇滚高音','情感真挚','创作才华','理想主义'],'Beyond乐队灵魂人物',['海阔天空','光辉岁月','真的爱你']],
['alan-tam','谭咏麟','Alan Tam','male',['粤语','经典','实力'],['温暖中音','气息稳定','情感丰富','舞台经验'],'粤语乐坛天皇巨星',['爱在深秋','水中花','一生中最爱']],
['yi-yangqianxi','易烊千玺','Jackson Yee','male',['流行','低音','新生代'],['低音磁性','情感内敛','叙事感','成长蜕变'],'新生代实力歌手',['冷静和疯狂','Fall','精彩才刚刚开始']],
['wang-yuan','王源','Roy Wang','male',['清新','创作','新生代'],['清亮中音','创作才华','情感真挚','成长风格'],'清新温暖的创作型新生代歌手',['十七','姑娘','阳光不锈']],
['mc-hotdog','MC HotDog','MC HotDog','male',['说唱','嘻哈','台湾'],['说唱技巧','flow多变','歌词犀利','嘻哈精神'],'台湾嘻哈教父',['差不多先生','我爱台妹','离开']],
['gai','GAI','GAI','male',['说唱','中国风','嘻哈'],['中国风说唱','flow流畅','歌词深度','舞台霸气'],'中国风说唱代表',['天干物燥','火锅底料','兰花草']],
['jony-j','Jony J','Jony J','male',['说唱','思想','深度'],['说唱技巧','歌词深度','思想性','flow稳定'],'思想型说唱歌手',['奴隶','Think Real','玩家']],
['knowknow','KnowKnow','KnowKnow','male',['说唱','时尚','旋律'],['旋律说唱','时尚感','flow流畅','Auto-Tune'],'时尚潮流说唱歌手',['R&B All Night','Midnight']],
['melo','Melo','Melo','male',['说唱','旋律','成都'],['旋律说唱','成都风格','flow丝滑','旋律感'],'成都旋律说唱代表',['Melo','在雨中','We Are']],
['huang-xuan','黄宣','YELLOW','male',['爵士','实验','创作'],['爵士唱腔','实验性','即兴能力','风格多变'],'台湾实验音乐才子',['独上C楼','怪天气']],
['zuo-xiao','左小祖咒','Zuoxiao Zuzhou','male',['实验','另类','先锋'],['独特唱法','跑调美学','实验性','反传统'],'极具争议的实验音乐人',['我不能悲伤地坐在你身旁','乌兰巴托的夜']],
['he-yong','何勇','He Yong','male',['摇滚','朋克','叛逆'],['朋克唱腔','嘶吼','叛逆精神','现场爆发'],'中国朋克摇滚代表',['垃圾场','姑娘漂亮','冬眠']],
['lay-zhang','张艺兴','Lay Zhang','male',['流行','唱跳','创作'],['唱跳实力','R&B转音','创作能力','舞台表现'],'全能型偶像',['莲','Sheep','梦不落雨林']],
['luhan','鹿晗','Lu Han','male',['流行','清新','偶像'],['清亮中音','R&B感觉','情感表达','舞台魅力'],'清新温暖的偶像歌手',['勋章','某时某刻','Replay']],
['ou-hao','欧豪','Ou Hao','male',['流行','说唱','偶像'],['说唱','中低音','舞台表现','青春活力'],'青春活力的偶像歌手',['破','Young','燃']],
['bai-jugang','白举纲','Bai Jugang','male',['摇滚','高音','力量'],['摇滚高音','力量感','嘶吼技巧','舞台爆发'],'充满力量的摇滚新生代',['弟子规','破茧']],
['chen-weiting','陈伟霆','William Chan','male',['唱跳','粤语','偶像'],['唱跳实力','中低音','粤语演唱','舞台魅力'],'唱跳俱佳的偶像歌手',['我我我','Warrior']],
['lin-feng','林峯','Raymond Lam','male',['粤语','偶像','抒情'],['中音温暖','粤语发音','偶像气质','情感表达'],'粤语偶像歌手',['爱在记忆中找你','直到你不找我']],
['xu-liang','徐良','Xu Liang','male',['网络','创作','抒情'],['温柔中音','创作才华','对唱技巧','网络风格'],'网络创作歌手',['客官不可以','红装']],
['wang-sulong','汪苏泷','Silence Wang','male',['创作','流行','网络'],['清亮中音','创作才华','旋律感','情感细腻'],'网络音乐创作才子',['不分手的恋爱','年轮','一笑倾城']],
['cao-ge','曹格','Gary Cao','male',['抒情','R&B','创作'],['R&B转音','高音细腻','创作才华','情感丰富'],'R&B创作歌手',['超级模范','背叛','寂寞先生']],
['lu-guanzhong','卢广仲','Crowd Lu','male',['独立','清新','创作'],['清新嗓音','吉他弹唱','自然风格','创作才华'],'清新自然的独立创作歌手',['鱼仔','刻在你心底的名字']],
['di-ke','迪克牛仔','Dick Cowboy','male',['摇滚','沧桑','翻唱'],['沙哑摇滚','沧桑感','高音撕裂','情感粗犷'],'沧桑沙哑的摇滚嗓音',['有多少爱可以重来','三万英尺']],
['a-du','阿杜','A-do','male',['沙哑','抒情','独特'],['极度沙哑','情感深沉','独特音色','高音悲怆'],'极度沙哑的独特嗓音',['他一定很爱你','坚持到底','天黑']],
['yang-pei-an','杨培安','Yang Peian','male',['摇滚','高音','实力'],['摇滚高音','嘶吼技巧','穿透力','力量感'],'实力摇滚高音歌手',['我相信','大海']],
['hu-xia','胡夏','Hu Xia','male',['抒情','清澈','OST'],['清澈高音','情感纯净','OST演唱','气息稳定'],'清澈温暖的抒情歌手',['那些年','知否知否','燃点']],
['ayunga','阿云嘎','Ayunga','male',['音乐剧','高音','蒙古族'],['音乐剧唱法','高音穿透','蒙古族元素','舞台表现'],'音乐剧歌手',['心之寻','鹿be free']],
['zheng-yunlong','郑云龙','Zheng Yunlong','male',['音乐剧','抒情','实力'],['音乐剧唱法','高音华丽','情感丰富','舞台魅力'],'音乐剧实力歌手',['我属于我自己','变身怪医']],
['ding-zhen','丁真','Ding Zhen','male',['藏族','原生态','纯净'],['原生态唱法','藏族元素','纯净嗓音','自然感'],'藏族原生态歌手',['1376心','Zood']],
['zhang-yuan','张远','Zhang Yuan','male',['抒情','偶像','温暖'],['温暖高音','情感细腻','偶像风格','气息稳定'],'温暖抒情的偶像歌手',['嘉宾','落魄']],
['chen-linong','陈立农','Chen Linong','male',['清新','偶像','温暖'],['清亮中音','温暖感','偶像气质','情感真挚'],'清新温暖的偶像歌手',['我是你','下半辈子']],
['fan-chengcheng','范丞丞','Fan Chengcheng','male',['说唱','偶像','活力'],['说唱','中低音','舞台活力','偶像风格'],'活力偶像说唱歌手',['I Will Find You','Run']],
['zhu-zhengting','朱正廷','Zhu Zhengting','male',['流行','唱跳','全能'],['唱跳全能','高音清亮','舞台表现','舞蹈功底'],'全能唱跳偶像',['K.O.','Flip']],
['huang-minghao','黄明昊','Justin Huang','male',['说唱','偶像','活力'],['说唱','中音活力','舞台表现','年轻风格'],'活力说唱偶像',['Liar','Hardcore']],
['huang-xu','黄旭','Huang Xu','male',['说唱','硬核','北京'],['硬核说唱','flow凶猛','北京风格','歌词深度'],'硬核说唱歌手',['Son of the World','Mad Man']],
['sujian','苏醒','Su Xing','male',['R&B','创作','全能'],['R&B转音','创作才华','全能型','舞台表现'],'全能R&B创作歌手',['心世界','进行式']],
['zhang-wei','张玮','Zhang Wei','male',['高音','实力','摇滚'],['超高音','摇滚力量','情感爆发','穿透力'],'极具爆发力的高音歌手',['高飞','英雄']],
['jin-zhiwen','金志文','Jin Zhiwen','male',['流行','创作','抒情'],['中音温暖','创作才华','编曲能力','情感表达'],'创作型歌手',['远走高飞','夏洛特烦恼']],
['liang-bo','梁博','Liang Bo','male',['摇滚','原创','实力'],['摇滚唱腔','高音穿透','原创能力','情感真挚'],'实力摇滚原创歌手',['男孩','灵魂歌手','日落']],
['quan-zhenye','权振东','Quan Zhendong','male',['摇滚','沧桑','实力'],['沙哑摇滚','沧桑感','高音力量','情感深沉'],'沧桑有力的摇滚歌手',['人质','春天里']],
['mao-ning','毛宁','Mao Ning','male',['流行','经典','抒情'],['温暖中音','经典风格','情感真挚','对唱技巧'],'经典流行男歌手',['涛声依旧','晚秋','心雨']],
['liu-yu','刘宇','Liu Yu','male',['国风','唱跳','新生代'],['国风演唱','唱跳实力','古典功底','舞台表现'],'国风唱跳新生代歌手',['山海','以梦为马']],
['huang-bo','黄渤','Huang Bo','male',['独特','质朴','跨界'],['质朴演唱','独特音色','情感真挚','舞台魅力'],'跨界歌手',['疯狂的石头','去大理']],
['tt-rapper','TT','TT','male',['说唱','潮流','年轻'],['说唱flow','潮流风格','年轻活力','旋律说唱'],'新生代潮流说唱歌手',['头文字T','在线等']],
['wang-yitai','王以太','Wang Yitai','male',['说唱','旋律','新生代'],['旋律说唱','Auto-Tune','flow多变','年轻风格'],'新生代旋律说唱歌手',['目不转睛','阿司匹林']],
['sheng-yu','盛宇','SHENG AI','male',['说唱','硬核','力量'],['硬核说唱','力量感','flow凶猛','舞台爆发'],'硬核说唱歌手',['就是南方','蹦迪']],
['c-block','C-BLOCK','C-BLOCK','male',['说唱','江湖','长沙'],['江湖说唱','flow沉稳','地域特色','歌词深度'],'江湖风格说唱团体',['江湖流','一代']],
['yu-bin','于斌','Yu Bin','male',['流行','唱跳','偶像'],['唱跳实力','中音稳定','舞台魅力','偶像风格'],'偶像唱跳歌手',['Fire','Mansion']],
['lin-mo','林墨','Lin Mo','male',['流行','清新','新生代'],['清新嗓音','情感细腻','自然演唱','年轻风格'],'清新新生代歌手',['如果','再见']],
['qin-fen','秦奋','Qin Fen','male',['流行','唱跳','偶像'],['唱跳实力','中低音','舞台魅力','偶像风格'],'唱跳偶像歌手',['Mister','Run To You']],
['sun-yizhou','孙亦洲','Sun Yizhou','male',['流行','偶像','唱跳'],['唱跳实力','中音稳定','舞台表现','偶像风格'],'偶像唱跳歌手',['世界','Young Blood']],
['hu-chunyang','胡春杨','Hu Chunyang','male',['流行','清新','新生代'],['清新嗓音','中音稳定','情感表达','年轻风格'],'清新新生代歌手',['世界上的另一个我','像风']],
['chen-feiyu','陈飞宇','Chen Feiyu','male',['流行','青春','偶像'],['青春嗓音','中音稳定','偶像风格','自然演唱'],'青春偶像歌手',['少年','光']],
['zhang-yunlong','张云龙','Zhang Yunlong','male',['流行','抒情','偶像'],['温暖中音','情感表达','偶像气质','自然演唱'],'温暖抒情的偶像歌手',['一个人的时光','其实']],
['zhang-zhehan','张哲瀚','Zhang Zhehan','male',['流行','抒情','偶像'],['温暖中音','情感真挚','偶像气质','OST演唱'],'偶像歌手',['你','别离开']],
// 华语女歌手
['deng-ziqi','邓紫棋','G.E.M.','female',['流行','高音','爆发力'],['爆发力高音','胸声共鸣','音域宽广','情感爆发'],'强大的爆发力和宽广的音域',['光年之外','泡沫','句号']],
['faye-wong','王菲','Faye Wong','female',['空灵','另类','梦幻'],['空灵音色','气声运用','梦幻感','独特咬字'],'空灵梦幻的音色',['传奇','红豆','匆匆那年']],
['zhang-huimei','张惠妹','A-Mei','female',['实力','高音','情感'],['高音爆发','情感张力','胸声厚度','技巧娴熟'],'极具爆发力的高音',['听海','解脱','我最亲爱的']],
['tian-fu-zhen','田馥甄','Hebe Tien','female',['清新','文艺','高音'],['清亮高音','气息控制','情感细腻','音色纯净'],'清亮纯净的音色',['小幸运','魔鬼中的天使','寂寞寂寞就好']],
['li-yuchun','李宇春','Chris Lee','female',['中性','流行','舞台'],['中低音磁性','舞台魅力','中性风格','时尚感'],'中性风格的流行歌手',['下个路口见','无问西东','流行']],
['zhou-bichang','周笔畅','Bibi Zhou','female',['R&B','中低音','实力'],['R&B转音','中低音磁性','灵魂感','情感表达'],'R&B风格的中低音实力歌手',['笔记','谁动了我的琴弦']],
['zhang-jingying','张靓颖','Jane Zhang','female',['高音','海豚音','实力'],['海豚音','超高音','音域宽广','情感张力'],'海豚音公主',['画心','如果这就是爱情','终于等到你']],
['shang-wenjie','尚雯婕','Laure Shang','female',['电子','实验','前卫'],['电子风格','实验性','高音穿透','前卫造型'],'前卫的电子音乐歌手',['最终信仰','Big Up']],
['stefanie-sun','孙燕姿','Stefanie Sun','female',['清新','抒情','经典'],['独特音色','情感真挚','中音温暖','辨识度极高'],'极具辨识度的独特嗓音',['天黑黑','遇见','我怀念的']],
['fish-leong','梁静茹','Fish Leong','female',['抒情','温暖','情歌'],['温暖中音','情感细腻','气息稳定','治愈系'],'情歌天后',['勇气','宁夏','可惜不是你']],
['teresa-teng','邓丽君','Teresa Teng','female',['经典','甜美','传奇'],['甜美嗓音','气息控制','情感温柔','完美音准'],'华语乐坛永恒传奇',['月亮代表我的心','甜蜜蜜','小城故事']],
['liu-ruoying','刘若英','Rene Liu','female',['温暖','文艺','叙事'],['温暖中音','叙事感强','情感自然','文艺气质'],'温暖知性的文艺歌手',['后来','很爱很爱你','成全']],
['cyndi-wang','王心凌','Cyndi Wang','female',['甜美','偶像','流行'],['甜美高音','偶像风格','清新感','旋律感'],'甜蜜教主',['爱你','睫毛弯弯','第一次爱的人']],
['rainie-yang','杨丞琳','Rainie Yang','female',['流行','抒情','偶像'],['中音稳定','情感表达','偶像转型','成长风格'],'从偶像到实力的蜕变歌手',['暧昧','年轮说','带我走']],
['elva-hsiao','萧亚轩','Elva Hsiao','female',['R&B','舞曲','中低音'],['中低音磁性','R&B转音','舞曲风格','时尚感'],'磁性中低音的R&B舞曲歌手',['最熟悉的陌生人','爱的主打歌','表白']],
['sandy-lam','林忆莲','Sandy Lam','female',['实力','抒情','多变'],['音域宽广','情感丰富','风格多变','技巧精湛'],'实力派天后',['至少还有你','伤痕','词不达意']],
['coco-lee','李玟','CoCo Lee','female',['R&B','舞曲','国际'],['R&B转音','舞曲实力','高音穿透','国际化'],'国际化R&B舞曲天后',['Di Da Do','好心情','月光爱人']],
['karen-mok','莫文蔚','Karen Mok','female',['独特','爵士','文艺'],['独特音色','爵士感','文艺气质','情感深邃'],'独特嗓音的文艺歌手',['阴天','盛夏的果实','慢慢喜欢你']],
['chen-qizhen','陈绮贞','Cheer Chen','female',['独立','清新','文艺'],['吉他弹唱','文艺气息','情感深邃','创作才华'],'台湾独立音乐才女',['旅行的意义','鱼','太阳']],
['yisa-yu','郁可唯','Yisa Yu','female',['抒情','实力','高音'],['高音穿透','情感爆发','气息控制','抒情实力'],'实力派抒情女歌手',['时间煮雨','指望','暖心']],
['zhang-bichen','张碧晨','Zhang Bichen','female',['抒情','高音','OST'],['高音穿透','情感张力','OST女王','气息绵长'],'OST女王',['年轮','凉凉','望']],
['yao-beina','姚贝娜','Yao Beina','female',['高音','实力','经典'],['超高音','胸声爆发','技巧精湛','情感浓烈'],'实力派高音歌手',['红颜劫','鱼','也许明天']],
['lala-hsu','徐佳莹','Lala Hsu','female',['创作','抒情','台湾'],['创作才华','高音细腻','情感丰富','风格多变'],'台湾创作才女',['失落沙洲','身骑白马','言不由衷']],
['chen-xuening','陈雪凝','Chen Xuening','female',['网络','抒情','新生代'],['温柔嗓音','情感细腻','网络热度','清新风格'],'新生代网络歌手',['你的酒馆对我打了烊','假装']],
['huang-ling','黄龄','Huang Ling','female',['转音','妖娆','独特'],['转音技巧','妖娆音色','音域宽广','独特风格'],'转音妖娆的独特女声',['痒','高跟','风月']],
['su-yunying','苏运莹','Su Yunying','female',['独特','创作','实验'],['独特唱法','创作才华','实验性','自然灵动'],'独特灵动的创作女歌手',['野子','萤火虫','冥明']],
['sitar-tan','谭维维','Sitar Tan','female',['摇滚','高音','民族'],['高音爆发','摇滚力量','民族元素','华阴老腔'],'融合民族与摇滚的实力歌手',['乌兰巴托的夜','给你一点颜色','如果有来生']],
['na-ying','那英','Na Ying','female',['实力','高音','北方'],['高音爆发','北方豪爽','情感直接','实力深厚'],'北方实力派天后',['征服','梦醒了','白天不懂夜的黑']],
['han-hong','韩红','Han Hong','female',['高音','公益','实力'],['超高音','穿透力极强','藏族元素','公益精神'],'超高音实力歌手',['天路','天亮了','家乡']],
['chen-lin','陈琳','Chen Lin','female',['摇滚','实力','经典'],['摇滚高音','情感爆发','实力演唱','经典风格'],'摇滚实力女歌手',['你的柔情我永远不懂','爱就爱了']],
['song-zuying','宋祖英','Song Zuying','female',['民歌','民族','殿堂'],['民歌高音','民族风格','殿堂级','传统功底'],'民歌殿堂级歌唱家',['好日子','小背篓','辣妹子']],
['peng-liyuan','彭丽媛','Peng Liyuan','female',['民歌','民族','殿堂'],['民歌高音','民族风格','殿堂级','艺术造诣'],'民族声乐艺术家',['在希望的田野上','父老乡亲']],
['lei-jia','雷佳','Lei Jia','female',['民歌','民族','实力'],['民歌高音','民族风格','实力深厚','舞台魅力'],'民族实力派歌唱家',['芦花','大地之心']],
['wu-qiong','吴琼','Wu Qiong','female',['民歌','民族','高音'],['民歌高音','民族风格','穿透力','传统功底'],'民族女高音歌唱家',['珠穆朗玛','青藏高原']],
['zhang-ye','张也','Zhang Ye','female',['民歌','民族','经典'],['民歌高音','民族风格','经典演绎','传统功底'],'民族声乐歌唱家',['走进新时代','万事如意']],
['li-guyu','李谷一','Li Guyi','female',['民歌','经典','殿堂'],['民歌高音','经典风格','殿堂级','气息控制'],'中国民歌殿堂级歌唱家',['难忘今宵','乡恋']],
['dong-wenjuan','董文华','Dong Wenhua','female',['民歌','军旅','经典'],['民歌高音','军旅风格','经典演绎','情感饱满'],'军旅民歌歌唱家',['春天的故事','望星空']],
['yang-yuying','杨钰莹','Yang Yuying','female',['甜美','经典','玉女'],['甜美至极','清纯嗓音','经典风格','甜歌皇后'],'甜歌皇后',['轻轻地告诉你','我不想说','心雨']],
['meng-tingwei','孟庭苇','Meng Tingwei','female',['甜美','经典','清纯'],['甜美清纯','高音飘逸','经典风格','少女感'],'甜美清纯的90年代玉女歌手',['风中有朵雨做的云','冬季到台北来看雨']],
['valen-hsu','许茹芸','Valen Hsu','female',['抒情','气声','独特'],['气声唱法','独特音色','高音飘逸','情感细腻'],'独特的气声唱法',['如果云知道','独角戏','日光机场']],
['winnie-hsin','辛晓琪','Winnie Hsin','female',['抒情','高音','经典'],['高音穿透','情感浓烈','经典风格','领悟力'],'抒情高音经典女歌手',['领悟','味道','女人何苦为难女人']],
['wan-fang','万芳','Wan Fang','female',['文艺','抒情','独特'],['独特音色','文艺气息','情感深邃','叙事感'],'文艺知性的独特女声',['新不了情','猜心','试心石']],
['panyueyun','潘越云','Pan Yueyun','female',['经典','抒情','低沉'],['低沉嗓音','情感深沉','经典风格','叙事感'],'低沉深情的经典女歌手',['我是不是你最疼爱的人','天天天蓝']],
['chenshu-hua','陈淑桦','Sarah Chen','female',['经典','温柔','抒情'],['温柔嗓音','情感细腻','经典风格','气息稳定'],'温柔细腻的经典女歌手',['梦醒时分','滚滚红尘','问']],
['qiqi','齐豫','Chyi Yu','female',['空灵','民谣','经典'],['空灵高音','民谣风格','天籁之音','情感超脱'],'天籁之音',['橄榄树','船歌','飞鸟']],
['huang-qishan','黄绮珊','Huang Qishan','female',['实力','高音','灵魂'],['灵魂唱腔','超高音','胸声爆发','转音技巧'],'实力唱将',['等待','灯塔']],
['jody-chiang','江蕙','Jody Chiang','female',['闽南','天后','经典'],['闽南语','情感丰富','天后再冠','韵味十足'],'闽南语天后',['家后','惜别的海岸','落雨声']],
['huang-fei','黄妃','Huang Fei','female',['闽南','实力','抒情'],['闽南语','高音穿透','情感浓烈','实力演唱'],'闽南语实力女歌手',['非常女','红桃2']],
['huang-yiling','黄乙玲','Huang Yiling','female',['闽南','经典','抒情'],['闽南语','情感深沉','经典风格','独特韵味'],'闽南语经典女歌手',['讲什么山盟海誓','放荡']],
['sally-chen','陈慧娴','Priscilla Chan','female',['粤语','经典','甜美'],['甜美高音','粤语经典','气息稳定','情感纯净'],'粤语乐坛公主',['千千阙歌','人生何处不相逢','傻女']],
['sammi-cheng','郑秀文','Sammi Cheng','female',['粤语','舞曲','实力'],['舞曲实力','粤语演唱','舞台魅力','情感表达'],'粤语乐坛天后',['眉飞色舞','终身美丽']],
['kelly-chen','陈慧琳','Kelly Chen','female',['粤语','流行','偶像'],['清亮嗓音','粤语流行','偶像风格','舞台表现'],'粤语流行偶像女歌手',['记事本','花花宇宙']],
['joey-yung','容祖儿','Joey Yung','female',['粤语','实力','舞台'],['实力演唱','粤语韵味','舞台魅力','情感丰富'],'粤语实力派天后',['小小','心淡','挥着翅膀的女孩']],
['miriam-yeung','杨千嬅','Miriam Yeung','female',['粤语','实力','抒情'],['情感真挚','中音温暖','粤语韵味','叙事感'],'粤语实力派女歌手',['再见二丁目','少女的祈祷','野孩子']],
['fiona-sit','薛凯琪','Fiona Sit','female',['粤语','甜美','偶像'],['甜美嗓音','粤语演唱','偶像风格','清新感'],'甜美清新的粤语偶像歌手',['小黑与我','男孩像你']],
['kary-ng','吴雨霏','Kary Ng','female',['粤语','实力','摇滚'],['摇滚唱腔','粤语实力','高音穿透','情感爆发'],'实力派粤语女歌手',['我本人','吴哥窟']],
['janice-vidal','卫兰','Janice Vidal','female',['粤语','R&B','独特'],['R&B唱腔','独特音色','粤语演唱','情感细腻'],'独特R&B风格的粤语女歌手',['大哥','爱才']],
['shirley-kwan','关淑怡','Shirley Kwan','female',['粤语','空灵','独特'],['空灵音色','独特风格','高音飘逸','情感深邃'],'空灵独特的粤语女歌手',['缱绻星光下','难得有情人']],
['huang-ying','黄莺','Huang Ying','female',['民歌','民族','高音'],['民歌高音','民族风格','穿透力','传统功底'],'民族女高音歌唱家',['山丹丹花开红艳艳','西部扬帆']],
['zu-hai','祖海','Zu Hai','female',['民歌','民族','实力'],['民歌高音','民族风格','实力深厚','情感饱满'],'民族实力派歌唱家',['好运来','幸福山歌','为了谁']],
['tang-can','汤灿','Tang Can','female',['民歌','民族','高音'],['民歌高音','民族风格','穿透力','舞台魅力'],'民族女高音歌唱家',['家乡美','天地喜洋洋']],
['chen-sisi','陈思思','Chen Sisi','female',['民歌','民族','甜美'],['民歌高音','甜美风格','民族元素','情感丰富'],'甜美民族女歌手',['你让我感动','美丽之路']],
['ren-ran','任然','Ren Ran','female',['网络','抒情','治愈'],['温柔嗓音','治愈感','情感细腻','网络热度'],'治愈系网络歌手',['飞鸟和蝉','空空如也']],
['chen-li','陈粒','Chen Li','female',['独立','民谣','文艺'],['独特音色','民谣风格','创作才华','自由随性'],'独立民谣女歌手',['奇妙能力歌','走马','小半']],
['zhang-xuan','张悬','Deserts Chang','female',['独立','民谣','文艺'],['吉他弹唱','文艺气息','情感深邃','创作才华'],'台湾独立音乐才女',['宝贝','玫瑰色的你']],
['daisy-tai','戴佩妮','Penny Tai','female',['创作','民谣','独立'],['吉他弹唱','创作才华','情感真挚','自然风格'],'马来西亚创作才女',['怎样','街角的祝福','野蔷薇']],
['tanya-chua','蔡健雅','Tanya Chua','female',['创作','都市','文艺'],['创作才华','中音温暖','都市感','情感细腻'],'新加坡创作才女',['空白格','达尔文','红色高跟鞋']],
['huang-xiaohu','黄小琥','Huang Xiaohu','female',['实力','爵士','低沉'],['爵士唱腔','低沉磁性','实力深厚','情感深邃'],'爵士女声',['没那么简单','不只是朋友']],
['olivia-ong','王俪婷','Olivia Ong','female',['爵士','Bossa Nova','清新'],['爵士唱腔','Bossa Nova','清新嗓音','国际化'],'爵士Bossa Nova歌手',['Fly Me to the Moon','Sea of Love']],
['al-huang','A-Lin','A-Lin','female',['抒情','高音','台湾'],['高音爆发','情感浓烈','抒情实力','音色磁性'],'台湾抒情实力女歌手',['给我一个理由忘记','有一种悲伤']],
['landy-wen','温岚','Landy Wen','female',['R&B','舞曲','原住民'],['R&B转音','舞曲实力','原住民力量','高音爆发'],'原住民R&B舞曲歌手',['屋顶','蓝色雨']],
['genie-chuo','卓文萱','Genie Chuo','female',['甜美','偶像','抒情'],['甜美嗓音','偶像风格','高音清亮','情感温柔'],'甜美偶像女歌手',['爱的城堡','幸福氧气']],
['liang-wenyin','梁文音','Rachel Liang','female',['抒情','高音','原住民'],['高音穿透','原住民血统','情感真挚','抒情实力'],'原住民抒情女歌手',['最幸福的事','爱其实很残忍']],
['wei-ru-xuan','魏如萱','Wei Ruxuan','female',['独立','文艺','实验'],['独特音色','文艺气息','实验风格','情感细腻'],'台湾独立文艺女歌手',['在不确定的世界里','彼个所在']],
['9m88','9m88','9m88','female',['爵士','R&B','实验'],['爵士唱腔','R&B感觉','实验性','独特风格'],'台湾爵士R&B新星',['平庸之上','九头身日奈']],
['fiona-fung','冯曦妤','Fiona Fung','female',['甜美','清新','广告'],['甜美嗓音','清新风格','广告歌曲','治愈感'],'甜美清新的广告歌曲歌手',['再见警察','Sunshine Girl']],
['vava-mao','万妮达','Vinida','female',['说唱','女性','力量'],['说唱实力','flow犀利','女性力量','舞台霸气'],'中国女性说唱代表',['我的新衣','Life is a Movie']],
['deng-ziqi-f','邓紫棋f','G.E.M. f','female',['流行','高音','粤语'],['爆发力高音','粤语演唱','国际风格','情感爆发'],'粤语实力女歌手',['光年之外','泡沫']],
];

fs.writeFileSync(path.join(OUT, 'chinese.ts'), gen(cn, 'chinese'));
console.log(`Chinese singers: ${cn.length}`);

// ===== 欧美歌手 ~200 =====
const west = [
// 欧美男歌手
['bruno-mars','Bruno Mars','Bruno Mars','male',['复古','灵魂','放克'],['复古灵魂','Falsetto','节奏感强','舞台表现力'],'复古灵魂乐风格',['Uptown Funk','24K Magic','Thats What I Like']],
['ed-sheeran','Ed Sheeran','Ed Sheeran','male',['民谣','流行','创作'],['叙事式演唱','吉他弹唱','情感真挚','loop技巧'],'叙事式的演唱方式',['Shape of You','Perfect','Thinking Out Loud']],
['the-weeknd','The Weeknd','The Weeknd','male',['R&B','迷幻','另类'],['迷幻假声','MJ式转音','暗色调','情感深沉'],'迷幻的假声',['Blinding Lights','Starboy','Cant Feel My Face']],
['sam-smith','Sam Smith','Sam Smith','male',['灵魂','抒情','高音'],['灵魂唱腔','高音细腻','情感爆发','性别模糊音色'],'极具灵魂感的唱腔',['Stay With Me','Too Good at Goodbyes']],
['frank-ocean','Frank Ocean','Frank Ocean','male',['另类R&B','实验','文艺'],['另类R&B','实验性','情感内敛','叙事性强'],'另类R&B风格',['Thinkin Bout You','Nights','Ivy']],
['justin-bieber','Justin Bieber','Justin Bieber','male',['流行','R&B','偶像'],['R&B转音','假声运用','情感表达','成长风格'],'从偶像到实力派',['Sorry','Love Yourself','Peaches']],
['shawn-mendes','Shawn Mendes','Shawn Mendes','male',['流行','创作','吉他'],['吉他弹唱','中音温暖','创作才华','情感真挚'],'吉他创作型歌手',['Stitches','Señorita','Treat You Better']],
['charlie-puth','Charlie Puth','Charlie Puth','male',['流行','创作','钢琴'],['钢琴弹唱','高音清亮','创作才华','和声能力'],'钢琴创作才子',['Attention','One Call Away','We Dont Talk Anymore']],
['john-legend','John Legend','John Legend','male',['灵魂','R&B','浪漫'],['灵魂唱腔','R&B感觉','浪漫嗓音','钢琴弹唱'],'浪漫灵魂歌手',['All of Me','Ordinary People','Green Light']],
['john-mayer','John Mayer','John Mayer','male',['蓝调','摇滚','吉他'],['吉他大师','蓝调唱腔','创作才华','中音磁性'],'吉他大师',['Gravity','Say','Waiting on the World to Change']],
['eric-clapton','Eric Clapton','Eric Clapton','male',['蓝调','摇滚','经典'],['蓝调吉他','沧桑嗓音','经典风格','情感深邃'],'蓝调吉他之神',['Tears in Heaven','Wonderful Tonight','Layla']],
['sting','Sting','Sting','male',['摇滚','爵士','文学'],['中音磁性','爵士感','文学性','贝斯功底'],'摇滚诗人',['Shape of My Heart','Englishman in New York','Every Breath You Take']],
['phil-collins','Phil Collins','Phil Collins','male',['流行','摇滚','鼓'],['中音温暖','鼓技精湛','创作才华','舞台魅力'],'摇滚鼓手兼歌手',['Another Day in Paradise','In the Air Tonight','Against All Odds']],
['elton-john','Elton John','Elton John','male',['流行','钢琴','经典'],['钢琴弹唱','高音华丽','经典风格','舞台华丽'],'钢琴摇滚传奇',['Rocket Man','Tiny Dancer','Your Song']],
['michael-buble','Michael Buble','Michael Buble','male',['爵士','流行','浪漫'],['爵士唱腔','浪漫嗓音','经典翻唱','舞台魅力'],'浪漫爵士歌手',['Haven t Met You Yet','Feeling Good','Its a Beautiful Day']],
['andrea-bocelli','Andrea Bocelli','Andrea Bocelli','male',['古典','歌剧','跨界'],['歌剧男高音','古典功底','跨界演唱','情感磅礴'],'跨界歌剧男高音',['Con te partiro','Time to Say Goodbye','The Prayer']],
['luciano-pavarotti','Luciano Pavarotti','Luciano Pavarotti','male',['歌剧','古典','殿堂'],['歌剧男高音','古典殿堂','穿透力极强','气息控制'],'世界三大男高音',['Nessun dorma','O Sole Mio','Caruso']],
['placido-domingo','Placido Domingo','Placido Domingo','male',['歌剧','古典','殿堂'],['歌剧男高音','古典功底','戏剧性','舞台统治力'],'世界三大男高音',['Granada','La Donna e Mobile']],
['freddie-mercury','Freddie Mercury','Freddie Mercury','male',['摇滚','歌剧','传奇'],['超高音','歌剧摇滚','舞台统治力','声线多变'],'皇后乐队传奇主唱',['Bohemian Rhapsody','Dont Stop Me Now','Somebody to Love']],
['david-bowie','David Bowie','David Bowie','male',['摇滚','实验','先锋'],['多变声线','实验性','艺术摇滚','前卫'],'摇滚变色龙',['Space Oddity','Heroes','Starman']],
['robert-plant','Robert Plant','Robert Plant','male',['摇滚','蓝调','高音'],['超高音','蓝调摇滚','嘶吼技巧','舞台魅力'],'齐柏林飞艇主唱',['Stairway to Heaven','Whole Lotta Love','Immigrant Song']],
['mick-jagger','Mick Jagger','Mick Jagger','male',['摇滚','蓝调','传奇'],['沙哑摇滚','蓝调感觉','舞台魅力','摇滚精神'],'滚石乐队主唱',['Satisfaction','Paint It Black','Gimme Shelter']],
['paul-mccartney','Paul McCartney','Paul McCartney','male',['流行','摇滚','经典'],['旋律天赋','中音温暖','创作才华','多乐器'],'披头士成员',['Yesterday','Hey Jude','Let It Be']],
['john-lennon','John Lennon','John Lennon','male',['摇滚','和平','传奇'],['独特音色','创作才华','思想性','摇滚精神'],'披头士灵魂人物',['Imagine','Let It Be','Give Peace a Chance']],
['george-michael','George Michael','George Michael','male',['流行','灵魂','R&B'],['灵魂唱腔','R&B转音','高音华丽','情感丰富'],'灵魂流行歌手',['Careless Whisper','Faith','Freedom']],
['prince','Prince','Prince','male',['放克','摇滚','天才'],['假声高音','多乐器','放克风格','舞台魅力'],'音乐天才',['Purple Rain','When Doves Cry','Kiss']],
['stevie-wonder','Stevie Wonder','Stevie Wonder','male',['灵魂','R&B','天才'],['灵魂唱腔','多乐器','创作天才','R&B经典'],'灵魂乐天才',['Superstition','I Just Called to Say I Love You','Signed Sealed Delivered']],
['marvin-gaye','Marvin Gaye','Marvin Gaye','male',['灵魂','R&B','经典'],['灵魂唱腔','柔滑高音','情感深邃','R&B经典'],'灵魂乐传奇',['Whats Going On','Lets Get It On','I Heard It Through the Grapevine']],
['otis-redding','Otis Redding','Otis Redding','male',['灵魂','蓝调','经典'],['灵魂嘶吼','蓝调感觉','情感浓烈','经典风格'],'灵魂乐之王',['Sittin on the Dock of the Bay','Try a Little Tenderness']],
['ray-charles','Ray Charles','Ray Charles','male',['灵魂','爵士','钢琴'],['灵魂唱腔','钢琴弹唱','爵士感觉','开创性'],'灵魂乐先驱',['Georgia on My Mind','Hit the Road Jack','Whatd I Say']],
['james-brown','James Brown','James Brown','male',['放克','灵魂','先驱'],['嘶吼唱法','放克节奏','舞台疯狂','开创性'],'放克之父',['I Got You','Papa Dont Take No Mess','Get Up']],
['bob-dylan','Bob Dylan','Bob Dylan','male',['民谣','摇滚','文学'],['独特嗓音','民谣风格','文学性','思想性'],'诺贝尔文学奖歌手',['Blowin in the Wind','Like a Rolling Stone','The Times They Are a-Changin']],
['neil-young','Neil Young','Neil Young','male',['摇滚','民谣','乡村'],['高音尖锐','吉他弹唱','民谣摇滚','思想性'],'加拿大摇滚传奇',['Heart of Gold','Rockin in the Free World','Old Man']],
['bruce-springsteen','Bruce Springsteen','Bruce Springsteen','male',['摇滚','蓝领','经典'],['沙哑摇滚','叙事感','蓝领精神','舞台耐力'],'美国蓝领摇滚之王',['Born to Run','Dancing in the Dark','Thunder Road']],
['tom-waits','Tom Waits','Tom Waits','male',['实验','爵士','独特'],['沙哑低沉','实验性','爵士感觉','独特风格'],'独特嗓音的实验音乐人',['Tom Trauberts Blues','Jersey Girl','Downtown Train']],
['leonard-cohen','Leonard Cohen','Leonard Cohen','male',['民谣','诗歌','深沉'],['低沉嗓音','诗歌朗诵','情感深邃','文学性'],'音乐诗人',['Hallelujah','Suzanne','Dance Me to the End of Love']],
['nick-cave','Nick Cave','Nick Cave','male',['哥特','摇滚','暗黑'],['低沉男中音','哥特风格','暗黑叙事','舞台魅力'],'暗黑摇滚诗人',['Red Right Hand','Into My Arms','Where the Wild Roses Grow']],
['thom-yorke','Thom Yorke','Thom Yorke','male',['另类','实验','电子'],['假声运用','实验性','电子元素','情感疏离'],'Radiohead主唱',['Creep','Karma Police','Everything in Its Right Place']],
['kurt-cobain','Kurt Cobain','Kurt Cobain','male',['垃圾摇滚','朋克','叛逆'],['嘶吼唱法','朋克精神','情感撕裂','吉他弹唱'],'Nirvana主唱',['Smells Like Teen Spirit','Come as You Are','Lithium']],
['axl-rose','Axl Rose','Axl Rose','male',['摇滚','高音','力量'],['超高音','摇滚嘶吼','力量感','舞台魅力'],'Guns N Roses主唱',['Sweet Child O Mine','Welcome to the Jungle','November Rain']],
['bono','Bono','Bono','male',['摇滚','公益','史诗'],['高音穿透','史诗感','公益精神','舞台魅力'],'U2主唱',['With or Without You','One','Beautiful Day']],
['matt-bellamy','Matt Bellamy','Matt Bellamy','male',['另类摇滚','高音','钢琴'],['超高音','钢琴摇滚','古典融合','实验性'],'Muse主唱',['Supermassive Black Hole','Starlight','Knights of Cydonia']],
['chris-martin','Chris Martin','Chris Martin','male',['另类摇滚','钢琴','抒情'],['假声运用','钢琴弹唱','情感细腻','旋律感强'],'Coldplay主唱',['Yellow','The Scientist','Fix You']],
['brendon-urie','Brendon Urie','Brendon Urie','male',['另类摇滚','高音','戏剧'],['超高音','戏剧性','风格多变','舞台张力'],'Panic at the Disco主唱',['High Hopes','I Write Sins Not Tragedies']],
['adam-lambert','Adam Lambert','Adam Lambert','male',['摇滚','高音','戏剧'],['超高音','戏剧性','摇滚力量','舞台华丽'],'摇滚高音歌手',['Whataya Want from Me','Ghost Town']],
['harry-styles','Harry Styles','Harry Styles','male',['流行','摇滚','时尚'],['中音温暖','摇滚感觉','时尚风格','情感表达'],'从偶像到艺术家',['Watermelon Sugar','As It Was','Adore You']],
['justin-timberlake','Justin Timberlake','Justin Timberlake','male',['流行','R&B','唱跳'],['R&B转音','假声技巧','唱跳实力','舞台魅力'],'流行R&B歌手',['Cry Me a River','SexyBack','Mirrors']],
['ricky-martin','Ricky Martin','Ricky Martin','male',['拉丁','流行','舞曲'],['拉丁唱腔','舞曲实力','高音穿透','舞台魅力'],'拉丁流行天王',['Livin la Vida Loca','She Bangs','Maria']],
['enrique-iglesias','Enrique Iglesias','Enrique Iglesias','male',['拉丁','流行','浪漫'],['浪漫嗓音','拉丁感觉','中音磁性','情感丰富'],'拉丁浪漫歌手',['Hero','Bailando','Subeme la Radio']],
['shaggy','Shaggy','Shaggy','male',['雷鬼','流行','独特'],['独特嗓音','雷鬼风格','节奏感强','舞台活力'],'雷鬼流行歌手',['Its Wasnt Me','Boombastic','Angel']],
['seal','Seal','Seal','male',['灵魂','抒情','独特'],['独特嗓音','灵魂感觉','情感深沉','高音细腻'],'灵魂抒情歌手',['Kiss from a Rose','Crazy','Killer']],
['aaron-neville','Aaron Neville','Aaron Neville','male',['灵魂','R&B','颤音'],['颤音技巧','灵魂唱腔','高音细腻','情感丰富'],'颤音灵魂歌手',['Tell It Like It Is','Dont Know Much']],
['boz-scaggs','Boz Scaggs','Boz Scaggs','male',['蓝调','摇滚','柔滑'],['柔滑中音','蓝调感觉','摇滚元素','经典风格'],'蓝调摇滚歌手',['Lowdown','Lido Shuffle','We Were All']],
['barry-white','Barry White','Barry White','male',['灵魂','放克','浪漫'],['超低音','灵魂唱腔','浪漫风格','放克节奏'],'低音灵魂歌手',['Cant Get Enough of Your Love','Youre the First the Last My Everything']],
['isaiah-firebrace','Isaiah Firebrace','Isaiah Firebrace','male',['流行','抒情','新生代'],['高音清亮','情感真挚','抒情实力','年轻风格'],'新生代抒情歌手',['So Close','What About Us']],
['daniel-caesar','Daniel Caesar','Daniel Caesar','male',['R&B','灵魂','另类'],['灵魂唱腔','R&B感觉','情感内敛','温柔嗓音'],'另类R&B歌手',['Best Part','Get You','Japanese Denim']],
['giveon','Giveon','Giveon','male',['R&B','灵魂','低音'],['超低音','灵魂感觉','浪漫风格','情感深沉'],'低音R&B歌手',['Heartbreak Anniversary','Like I Want You']],
['sza','SZA','SZA','female',['R&B','另类','实验'],['R&B唱腔','实验性','情感丰富','独特风格'],'另类R&B女歌手',['Good Days','Kill Bill','The Weekend']],
// 欧美女歌手
['adele','Adele','Adele','female',['灵魂','抒情','力量'],['胸声厚度','情感颤音','力量感','情感共鸣'],'深厚的胸声和极具感染力的情感颤音',['Rolling in the Deep','Someone Like You','Hello']],
['taylor-swift','Taylor Swift','Taylor Swift','female',['流行','乡村','叙事'],['叙事式演唱','乡村气息','情感表达','旋律感强'],'叙事式的演唱方式',['Love Story','Shake It Off','Blank Space']],
['billie-eilish','Billie Eilish','Billie Eilish','female',['另类','暗黑','实验'],['气声耳语','ASMR感','低音区','氛围感'],'气声耳语式演唱',['Bad Guy','Happier Than Ever','Lovely']],
['ariana-grande','Ariana Grande','Ariana Grande','female',['流行','R&B','高音'],['花腔高音','R&B转音','海豚音','音域宽广'],'花腔高音和精湛的R&B转音',['7 Rings','Thank U Next','Positions']],
['dua-lipa','Dua Lipa','Dua Lipa','female',['流行','迪斯科','舞曲'],['中低音磁性','节奏感强','舞曲风格','复古感'],'磁性的中低音',['Levitating','Dont Start Now','Physical']],
['beyonce','Beyonce','Beyonce','female',['R&B','力量','舞台'],['胸声爆发','R&B转音','舞台统治力','声乐技巧极致'],'R&B天后',['Halo','Crazy in Love','Formation']],
['rihanna','Rihanna','Rihanna','female',['流行','R&B','舞曲'],['中低音磁性','R&B感觉','舞曲风格','时尚感'],'流行舞曲天后',['Umbrella','Diamonds','Work']],
['katy-perry','Katy Perry','Katy Perry','female',['流行','电子','活力'],['中音稳定','电子风格','活力演唱','旋律感强'],'流行活力歌手',['Firework','Roar','Teenage Dream']],
['lady-gaga','Lady Gaga','Lady Gaga','female',['流行','实验','舞台'],['音域宽广','实验风格','舞台震撼','多才多艺'],'实验流行天后',['Bad Romance','Poker Face','Shallow']],
['madonna','Madonna','Madonna','female',['流行','舞曲','先锋'],['中音稳定','舞曲风格','先锋精神','舞台革新'],'流行女皇',['Like a Virgin','Material Girl','Vogue']],
['whitney-houston','Whitney Houston','Whitney Houston','female',['灵魂','高音','殿堂'],['超高音','胸声爆发','颤音完美','声乐教科书'],'声乐教科书',['I Will Always Love You','Greatest Love of All','I Wanna Dance with Somebody']],
['mariah-carey','Mariah Carey','Mariah Carey','female',['R&B','高音','海豚音'],['海豚音','R&B转音','花腔技巧','音域极广'],'海豚音天后',['We Belong Together','Hero','Vision of Love']],
['celine-dion','Celine Dion','Celine Dion','female',['抒情','高音','力量'],['超高音','气息控制','力量感','情感磅礴'],'力量抒情天后',['My Heart Will Go On','The Power of Love','All by Myself']],
['shania-twain','Shania Twain','Shania Twain','female',['乡村','流行','跨界'],['乡村流行','高音清亮','跨界风格','旋律感强'],'乡村流行天后',['Man! I Feel Like a Woman','Youre Still the One']],
['dolly-parton','Dolly Parton','Dolly Parton','female',['乡村','民谣','经典'],['高音甜美','乡村风格','创作才华','经典永恒'],'乡村音乐传奇',['Jolene','9 to 5','I Will Always Love You']],
['aretha-franklin','Aretha Franklin','Aretha Franklin','female',['灵魂',' gospel','殿堂'],['灵魂唱腔',' gospel风格','超高音','声乐极致'],'灵魂乐女王',['Respect','Natural Woman','Think']],
['tina-turner','Tina Turner','Tina Turner','female',['摇滚','灵魂','舞台'],['沙哑摇滚','灵魂力量','舞台爆发','能量无穷'],'摇滚女王',['Whats Love Got to Do with It','Proud Mary','Private Dancer']],
['janis-joplin','Janis Joplin','Janis Joplin','female',['摇滚','蓝调','传奇'],['嘶吼唱法','蓝调感觉','情感撕裂','舞台疯狂'],'蓝调摇滚传奇',['Piece of My Heart','Summertime','Mercedes Benz']],
['stevie-nicks','Stevie Nicks','Stevie Nicks','female',['摇滚','民谣','神秘'],['独特音色','民谣摇滚','神秘气质','创作才华'],'Fleetwood Mac女主唱',['Landslide','Dreams','Rhiannon']],
['kate-bush','Kate Bush','Kate Bush','female',['实验','艺术','先锋'],['高音飘逸','实验性','艺术风格','前卫创作'],'实验音乐先锋',['Running Up That Hill','Wuthering Heights','Babooshka']],
['bjork','Bjork','Bjork','female',['实验','电子','先锋'],['独特声线','实验电子','前卫风格','自然灵感'],'冰岛实验音乐精灵',['It Oh So Quiet','Hyperballad','Army of Me']],
['sia','Sia','Sia','female',['流行','高音','神秘'],['高音穿透','情感爆发','神秘风格','创作才华'],'神秘高音歌手',['Chandelier','Cheap Thrills','Elastic Heart']],
['lana-del-rey','Lana Del Rey','Lana Del Rey','female',['另类','复古','梦幻'],['低音磁性','复古风格','梦幻氛围','电影感'],'复古梦幻歌手',['Video Games','Summertime Sadness','Born to Die']],
['lorde','Lorde','Lorde','female',['另类','电子','文艺'],['中低音磁性','电子风格','文艺气息','极简制作'],'另类电子歌手',['Royals','Green Light','Team']],
['miley-cyrus','Miley Cyrus','Miley Cyrus','female',['流行','摇滚','叛逆'],['沙哑中音','摇滚感觉','叛逆精神','风格多变'],'叛逆流行歌手',['Wrecking Ball','Flowers','Party in the USA']],
['selena-gomez','Selena Gomez','Selena Gomez','female',['流行','抒情','偶像'],['中音温暖','抒情风格','偶像转型','情感表达'],'流行偶像歌手',['Lose You to Love Me','Wolves','Good for You']],
['camila-cabello','Camila Cabello','Camila Cabello','female',['流行','拉丁','R&B'],['拉丁感觉','R&B转音','中音磁性','舞台魅力'],'拉丁流行歌手',['Havana','Senorita','Never Be the Same']],
['doja-cat','Doja Cat','Doja Cat','female',['说唱','流行','实验'],['说唱技巧','流行感觉','实验风格','多变形象'],'说唱流行歌手',['Say So','Kiss Me More','Woman']],
['cardi-b','Cardi B','Cardi B','female',['说唱','嘻哈','力量'],['说唱实力','flow凶猛','舞台霸气','个性鲜明'],'嘻哈女歌手',['Bodak Yellow','WAP','I Like It']],
['nicki-minaj','Nicki Minaj','Nicki Minaj','female',['说唱','嘻哈','多变'],['说唱技巧','多变声线','flow多变','舞台霸气'],'嘻哈女王',['Super Bass','Anaconda','Starships']],
['megan-thee-stallion','Megan Thee Stallion','Megan Thee Stallion','female',['说唱','嘻哈','力量'],['说唱实力','flow犀利','女性力量','自信风格'],'嘻哈新生代',['Savage','Body','Hot Girl Summer']],
['halsey','Halsey','Halsey','female',['另类','流行','暗黑'],['中低音磁性','暗黑风格','情感直接','实验性'],'另类暗黑歌手',['Without Me','Bad at Love','Graveyard']],
['lizzo','Lizzo','Lizzo','female',['R&B','流行','自信'],['R&B唱腔','自信风格','长笛演奏','正能量'],'自信R&B歌手',['Truth Hurts','Good as Hell','About Damn Time']],
['olivia-rodrigo','Olivia Rodrigo','Olivia Rodrigo','female',['流行','朋克','青春'],['情感爆发','朋克元素','青春感','创作才华'],'青春流行歌手',['drivers license','good 4 u','deja vu']],
['sabrina-carpenter','Sabrina Carpenter','Sabrina Carpenter','female',['流行','甜美','创作'],['甜美嗓音','创作才华','流行感觉','年轻风格'],'甜美创作歌手',['Nonsense','Feather','Espresso']],
['dua-lipa-2','Dua Lipa 2','Dua Lipa 2','female',['迪斯科','流行','复古'],['中低音磁性','复古迪斯科','舞曲风格','时尚感'],'复古迪斯科风',['Physical','Break My Heart']],
['kacey-musgraves','Kacey Musgraves','Kacey Musgraves','female',['乡村','流行','文艺'],['乡村流行','高音清亮','文艺气息','创作才华'],'乡村文艺歌手',['Golden Hour','Follow Your Arrow','Space Cowboy']],
['maren-morris','Maren Morris','Maren Morris','female',['乡村','流行','跨界'],['乡村流行','高音穿透','跨界风格','创作才华'],'乡村跨界歌手',['The Middle','My Church','80s Mercedes']],
['kelsea-ballerini','Kelsea Ballerini','Kelsea Ballerini','female',['乡村','流行','年轻'],['乡村流行','高音甜美','年轻风格','旋律感强'],'乡村年轻歌手',['Love Me Like You Mean It','Peter Pan','Miss Me More']],
['carrie-underwood','Carrie Underwood','Carrie Underwood','female',['乡村','高音','实力'],['超高音','乡村风格','实力演唱','情感爆发'],'乡村实力歌手',['Before He Cheats','Blown Away','Jesus Take the Wheel']],
['miranda-lambert','Miranda Lambert','Miranda Lambert','female',['乡村','摇滚','真实'],['沙哑乡村','摇滚元素','真实感','创作才华'],'乡村摇滚女歌手',['The House That Built Me','Mama','Automatic']],
['norah-jones','Norah Jones','Norah Jones','female',['爵士','民谣','治愈'],['爵士唱腔','治愈嗓音','钢琴弹唱','慵懒感觉'],'治愈爵士歌手',['Dont Know Why','Come Away with Me','Sunrise']],
['amy-winehouse','Amy Winehouse','Amy Winehouse','female',['灵魂','爵士','复古'],['灵魂唱腔','爵士感觉','复古风格','情感深沉'],'复古灵魂歌手',['Rehab','Back to Black','Valerie']],
['dua-lipa-3','Adele 2','Adele 2','female',['灵魂','英国','经典'],['胸声厚度','英国灵魂','经典风格','情感共鸣'],'英国灵魂乐代表',['Set Fire to the Rain','Skyfall','Water Under the Bridge']],
['florence-welch','Florence Welch','Florence Welch','female',['独立','摇滚','史诗'],['高音穿透','史诗感','独立摇滚','舞台张力'],'Florence + the Machine主唱',['Dog Days Are Over','Shake It Out','Hunger']],
['st-vincent','St Vincent','St Vincent','female',['实验','摇滚','吉他'],['实验摇滚','吉他技巧','独特风格','前卫'],'实验摇滚女歌手',['Masseduction','Los Ageless','Cruel']],
['fiona-apple','Fiona Apple','Fiona Apple','female',['另类','钢琴','实验'],['钢琴弹唱','另类风格','实验性','情感深邃'],'另类钢琴女歌手',['Criminal','Paper Bag','Fast as You Can']],
['tori-amos','Tori Amos','Tori Amos','female',['另类','钢琴','艺术'],['钢琴弹唱','另类风格','艺术性','情感深邃'],'另类钢琴艺术家',['Silent All These Years','Cornflake Girl','Precious Things']],
['alanis-morissette','Alanis Morissette','Alanis Morissette','female',['摇滚','另类','90年代'],['摇滚嘶吼','另类风格','情感直接','吉他弹唱'],'90年代摇滚女声',['You Oughta Know','Hand in My Pocket','Ironic']],
['sheryl-crow','Sheryl Crow','Sheryl Crow','female',['摇滚','乡村','民谣'],['中音磁性','摇滚乡村','吉他弹唱','创作才华'],'摇滚乡村女歌手',['If It Makes You Happy','Strong Enough','All I Wanna Do']],
['melissa-etheridge','Melissa Etheridge','Melissa Etheridge','female',['摇滚','蓝调','力量'],['沙哑摇滚','蓝调感觉','力量感','吉他弹唱'],'摇滚力量女声',['Come to My Window','I Will Not Be Broken']],
['bonnie-raitt','Bonnie Raitt','Bonnie Raitt','female',['蓝调','摇滚','吉他'],['蓝调吉他','滑棒技巧','沙哑嗓音','情感深邃'],'蓝调吉他女歌手',['Something to Talk About','I Cant Make You Love Me']],
['dido','Dido','Dido','female',['电子','民谣','治愈'],['温柔嗓音','电子民谣','治愈感','氛围感'],'治愈电子民谣歌手',['Thank You','White Flag','Life for Rent']],
['imogen-heap','Imogen Heap','Imogen Heap','female',['电子','实验','人声'],['人声实验','电子制作','实验性','技术创新'],'电子实验音乐人',['Hide and Seek','Headlock','First Train Home']],
['grimes','Grimes','Grimes','female',['电子','实验','先锋'],['电子制作','实验风格','先锋感','多乐器'],'电子实验先锋',['Oblivion','Genesis','Kill V Maim']],
['fka-twigs','FKA Twigs','FKA Twigs','female',['实验','R&B','前卫'],['实验R&B','前卫风格','舞蹈功底','视觉艺术'],'前卫实验歌手',['Two Weeks','Pendulum','Cellophane']],
['kelela','Kelela','Kelela','female',['R&B','电子','另类'],['另类R&B','电子元素','空灵声线','氛围感'],'另类R&B歌手',['Take Me Apart','Frontline','LMK']],
['jhene-aiko','Jhene Aiko','Jhene Aiko','female',['R&B','灵魂','治愈'],['R&B唱腔','治愈嗓音','灵魂感觉','情感细腻'],'治愈R&B歌手',['The Worst','Sativa','Triggered']],
['h-e-r','H.E.R.','H.E.R.','female',['R&B','灵魂','吉他'],['R&B唱腔','吉他弹唱','灵魂感觉','情感真挚'],'R&B吉他女歌手',['Focus','Best Part','Damage']],
['summer-walker','Summer Walker','Summer Walker','female',['R&B','灵魂','情感'],['R&B唱腔','情感深沉','灵魂感觉','治愈感'],'情感R&B歌手',['Playing Games','Come Thru','Girls Need Love']],
['sza-2','SZA 2','SZA 2','female',['R&B','另类','自然'],['R&B唱腔','另类风格','自然感','情感真实'],'另类R&B代表',['The Weekend','Love Galore','Supermodel']],
['ellie-goulding','Ellie Goulding','Ellie Goulding','female',['电子','流行','空灵'],['空灵高音','电子风格','清新感','旋律感强'],'空灵电子流行歌手',['Lights
